# Generated by Django 5.2.7 on 2025-10-05 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(db_column='idRol', primary_key=True, serialize=False)),
                ('nombreRol', models.CharField(db_column='nombreRol', max_length=50)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('estado', models.BooleanField(db_column='estado', default=True)),
            ],
            options={
                'db_table': 'Rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioPersonalizado',
            fields=[
                ('id', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='nombres', max_length=100)),
                ('apellidos', models.CharField(db_column='apellidos', max_length=100)),
                ('correo', models.EmailField(db_column='correo', max_length=254, unique=True)),
                ('contrasena', models.CharField(db_column='contraseña', max_length=255)),
                ('idRol', models.ForeignKey(blank=True, db_column='idRol', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.rol')),
            ],
            options={
                'db_table': 'Usuario',
                'managed': True,
            },
        ),
    ]
