# Generated by Django 5.2.7 on 2025-10-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariopersonalizado',
            old_name='contrasena',
            new_name='password',
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
        migrations.AlterModelTable(
            name='usuariopersonalizado',
            table='usuario',
        ),
    ]
