# Generated by Django 5.2.7 on 2025-10-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_contrasena_usuariopersonalizado_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='password',
            field=models.CharField(db_column='contrasena', max_length=255),
        ),
    ]
